# -*- coding: utf-8 -*-
"""1ra entrega.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O68_OOHHmgqVImVj6s7vHvxlzt4ouxMW
"""

import pandas as pd
url="https://raw.githubusercontent.com/NataliaForer0/Basededatos/main/unemploy.csv"
df=pd.read_csv(url,sep=",")
type(df)

df.head(10)

df.dtypes

df.info()

df['1990 [YR1990]'] = pd.to_numeric(df['1990 [YR1990]'], errors='coerce')
df['2000 [YR2000]'] = pd.to_numeric(df['2000 [YR2000]'], errors='coerce')
df['2012 [YR2012]'] = pd.to_numeric(df['2012 [YR2012]'], errors='coerce')
df['2013 [YR2013]'] = pd.to_numeric(df['2013 [YR2013]'], errors='coerce')
df['2014 [YR2014]'] = pd.to_numeric(df['2014 [YR2014]'], errors='coerce')
df['2015 [YR2015]'] = pd.to_numeric(df['2015 [YR2015]'], errors='coerce')
df['2016 [YR2016]'] = pd.to_numeric(df['2016 [YR2016]'], errors='coerce')
df['2017 [YR2017]'] = pd.to_numeric(df['2017 [YR2017]'], errors='coerce')
df['2018 [YR2018]'] = pd.to_numeric(df['2018 [YR2018]'], errors='coerce')
df['2019 [YR2019]'] = pd.to_numeric(df['2019 [YR2019]'], errors='coerce')
df['2020 [YR2020]'] = pd.to_numeric(df['2020 [YR2020]'], errors='coerce')
df['2021 [YR2021]'] = pd.to_numeric(df['2021 [YR2021]'], errors='coerce')
df.dtypes

df.describe()

df['Series Name'].unique()

df[df['Series Name'] == ' male (% of male labor force) (modeled ILO estimate)']

df[df['Series Name'] == ' female (% of female labor force) (modeled ILO estimate)']

#Las variables que considero mas relevantes de esta base de datos es: "Series name", ya que permite identificar que población es la que se esta evaluando, el country name ya que me permite ubicar geograficamente las cifras, adicional los años que me permitira evaluar estas cifras atraves del tiempo.