# -*- coding: utf-8 -*-
"""1ra entrega_2dabase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kfw1HnQKsFiDPBWs6uPHO9NlefCSAY8-
"""

import pandas as pd 
url ='https://raw.githubusercontent.com/NataliaForer0/Basededatos/main/Salidas_de_colombianos_desde_el_territorio_nacional.csv'
df=pd.read_csv(url,sep=",")
type(df)

df.head(10)

df.dtypes

df.info()

df.describe()

df['País destino'].unique()

df['País destino'].value_counts()

import matplotlib.pyplot as plt
import matplotlib
plt.plot(df['País destino'],df['Total'])

df.sort_values('Total',ascending=False)

# Las variables que considero mas importantes son el total, pais destino y las columnas femenino y masculino. Esta información me permite analizar que cantidad de hombres y mujeres salen del  pais y cual es su destino